version: 2
jobs:
  build:
    docker:
      - image: jagregory/pandoc

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: create pdfs
          command: |
            make

      - store_artifacts:
          path: 'out'
          
